Repository my-trash-bin/rt, pull requests merged in 2025-06, with the labels that each got.

#1 Add repository documentation
  AGENTS.md
  README.md
Labels: codex

#2 Add jsonc FFI wrapper and fix double free
  .vscode/settings.json
  Cargo.toml
  README.md
  input.scene.rt
  json/Cargo.toml
  json/src/lib.rs
  json_minifier_cli/Cargo.toml
  json_minifier_cli/src/main.rs
  jsonc/Cargo.toml
  jsonc/build.rs
  jsonc/include/jsonc.h
  jsonc/init.sh
  jsonc/native/jsonc.c
  jsonc/src/bindings.rs
  jsonc/src/lib.rs
  rt/Cargo.toml
  rt/src/main.rs
  scene/Cargo.toml
  scene/src/camera/mod.rs
  scene/src/camera/perspective.rs
  scene/src/lib.rs
  scene/src/light/mod.rs
Labels: codex

#5 chore : add github template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: enhancement

#3 Add direct scene parsing
  README.md
  rt/src/main.rs
  scene/src/camera/mod.rs
  scene/src/camera/perspective.rs
  scene/src/lib.rs
  scene/src/light/mod.rs
Labels: codex

#10 Fix long-flag formatting error
  rt/src/main.rs
Labels: bug
